spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanjiamall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  support-methods-arguments: true
  reasonable: true
  helper-dialect: mysql




jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


#这些路径需要放行的
secure:
  ignored:
    urls:
      - /**
      - /chat/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/doc.html
      - /api/admin/login  # 登录路径
      - /api/upload    # 图片上传路径
      - /wx/**      # 微信端访问的路径


wanjiamall:
  # 快鸟物流查询配置
  express:
    enable: true
    appId: "test1625113"
    appKey: "f5d20ce4-21f1-4125-a703-650e2d73ca30"
    vendors:
      - code: "ZTO"
        name: "中通快递"
      - code: "YTO"
        name: "圆通速递"
      - code: "YD"
        name: "韵达速递"
      - code: "YZPY"
        name: "邮政快递包裹"
      - code: "EMS"
        name: "EMS"
#      - code: "DBL"
#        name: "德邦快递"
#      - code: "FAST"
#        name: "快捷快递"
#      - code: "ZJS"
#        name: "宅急送"
#      - code: "TNT"
#        name: "TNT快递"
#      - code: "UPS"
#        name: "UPS"
#      - code: "DHL"
#        name: "DHL"
#      - code: "FEDEX"
#        name: "FEDEX联邦(国内件)"
#      - code: "FEDEX_GJ"
#        name: "FEDEX联邦(国际件)"
#server:
#  port: 8082
