spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanjiamall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml

pagehelper:
  support-methods-arguments: true
  reasonable: true
  helper-dialect: mysql
