spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanjiamall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  support-methods-arguments: true
  reasonable: true
  helper-dialect: mysql




jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


#这些路径需要放行的
secure:
  ignored:
    urls:
      - /**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/doc.html
      - /api/admin/login  # 登录路径
      - /api/upload    # 图片上传路径
      - /wx/**      # 微信端访问的路径
